#!/bin/bash

Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }


# Getting
export CHATID="1849721300"
export KEY="5765384772:AAGUVlNWYF5vwvHgALKFSSu6saMCPl8F3dg"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"


clear
echo -e ""
echo -e " 01. Creating Vmess Account"
echo -e " 02. Creating Trial Vmess Account"
echo -e " 03. Delete Vmess Account"
echo -e " 04. Renew Vmess Account"
echo -e " 05. Check Vmess login Account"
echo -e " 06. Check Config Vmess Account"
echo -e ""
read -p "Select Options [ 1 - 6 ] : " menu
case $menu in
1)   clear ;
    addws
    ;;
2) clear ;
    trialws
    ;;
3) clear ;
    delws
    ;;
4) clear ;
    renewws
    ;;
5) clear ;
    cekws
    ;;
6) clear ;
    user-ws
    ;;
*) clear ;
    menu
    ;;
esac
